openapi: 3.1.0
info:
  version: 1.0.0
  title: lanjingerp openApi
  termsOfService: 'https://master.lanjingerp.com/'
  #contact:
    #email: contact@example.com
    #url: 'http://example.com/contact'
  #license:
    #name: Apache 2.0
    #url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  #x-logo:
    #url: 'https://m.media-amazon.com/images/S/abs-image-upload-na/1/AmazonStores/A1PA6795UKMFR9/6d3127e6ecf5667460853a3f3035c591.w2276.h2276._CR0%2C0%2C2276%2C2276_SX2276_.png'
  #description:
    #$ref: ./info-description.md
tags:
  - name: Echo
    description: Example echo operations.
  - name: User
    description: Operations about users.
  - name: Tag
    description: This is a tag description.
  - name: ms-user
    description: This is a ms-user description.
servers:
  - url: 'https://dev-backend.lanjingerp.com'
    #variables:
      #tenant:
        #default: www
        #description: Your tenant id
  #- url: 'https://dev-backend.lanjingerp.com/'
paths:
  '/users/{username}':
    $ref: 'paths/users_{username}.yaml'
  /echo:
    $ref: paths/echo.yaml
  /pathItem:
    $ref: paths/path-item.yaml
  /pathItemWithExamples:
    $ref: paths/path-item-with-examples.yaml
  /user/rest/v2/login:
    $ref: paths/ms-user.yaml
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
